name: commit-lint

on:
  pull_request:
    branches:
      - main

jobs:
  lint-commits:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: git fetch --depth=0

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install @commitlint/{cli,config-conventional}

      - run: npx commitlint --from=$(git merge-base HEAD origin/main) --to=HEAD
