name: Release Please

permissions:
  id-token: write
  contents: write
  pull-requests: write

on:
  push:
    paths:
      - packages/**
    branches:
      - main

jobs:
  deploy:
    name: Deploy service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target-branch: main
          include-component-in-tag: true
          manifest-file: .release-please-manifest.json
          config-file: .release-please-config.json
