name: Release Please

on:
  push:
    paths:
      - 'packages/**/pyproject.toml'
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: List changed files
        id: get_changed_files
        run: |          
          # Get the list of changed files between commits
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          
          echo "Changed files:"
          echo "$CHANGED_FILES"
          
          # Convert newline-separated list to a comma-separated list
          CHANGED_FILES_CSV=$(echo "$CHANGED_FILES" | tr '\n' ',' | sed 's/,$//')
          
          # Set the output
          echo "changed_files=$CHANGED_FILES_CSV" >> "$GITHUB_OUTPUT"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: latest

      - name: Install toml-cli
        run: uv add toml-cli

      - name: Extract versions from changed files
        id: get_versions
        run: |
          # Initialize an empty JSON object
          JSON_OUTPUT="{}"
          
          # Access the list of changed files
          CHANGED_FILES="${{ steps.get_changed_files.outputs.changed_files }}"
          
          # Split the comma-separated list into an array
          IFS=',' read -r -a FILE_ARRAY <<< "$CHANGED_FILES"
          
          for FILE in "${FILE_ARRAY[@]}"; do
            # Check if the file matches the pattern 'packages/*/pyproject.toml'
            if [[ "$FILE" =~ ^packages/[^/]+/pyproject\.toml$ ]]; then
              echo "Processing $FILE..."
              
              # Get the version using uv
              VERSION=$(uv run toml get --toml-path "$FILE" project.version)
              
              # Extract the package name
              PACKAGE_PATH=$(dirname "$FILE")
              PACKAGE_NAME=$(echo "$PACKAGE_PATH" | sed 's/packages\///' | sed 's/\//-/g')
              
              # Add the package and its version to the JSON object
              JSON_OUTPUT=$(echo "$JSON_OUTPUT" | jq --arg package "packages/$PACKAGE_NAME" --arg version "$VERSION" '. + {($package): $version}')
              
              echo "Updated JSON: $JSON_OUTPUT"
            else
              echo "Skipping $FILE: does not match the pattern 'packages/*/pyproject.toml'"
            fi
          done
          
          # Write the updated JSON to the .release-please-manifest.json file
          echo "$JSON_OUTPUT" > .release-please-manifest.json

      - name: Display updated manifest
        run: |
          echo "Updated .release-please-manifest.json:"
          cat .release-please-manifest.json

      - name: Run Release Please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target-branch: main
          include-component-in-tag: true 
